version: 0.2

phases:
  build:
    commands:
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name pearls-aqi-api --image-uri $REPOSITORY_URI:latest
      - aws lambda wait function-updated --function-name pearls-aqi-api
      - aws lambda update-function-code --function-name pearls-aqi-feature-pipeline --image-uri $REPOSITORY_URI:latest
      - aws lambda wait function-updated --function-name pearls-aqi-feature-pipeline
      - echo "Deploy successful!"
